"""
Lean Windows training script for the "ok kimi" wake-word model.

Mirrors the openWakeWord `train.py` flow but skips Piper clip generation
(Linux-only) — clips are pre-generated by `gen_clips.py` (edge-tts). Uses the
openwakeword library API directly:

  augment_clips -> compute_features_from_generator -> mmap_batch_generator
  -> Model.auto_train -> export_model (ONNX)

Usage:
  python tools/kimi_wake/train_wake.py [--steps N] [--data DIR]

Outputs kimi_wake.onnx (+ tflite if onnx2tf available) into the data dir.
"""

import argparse
import glob
import logging
import os
import sys
from pathlib import Path

import numpy as np
import scipy.io.wavfile
import torch

# openwakeword must be importable (pip install -e D:/DEV/openWakeWord)
import openwakeword
from openwakeword.data import augment_clips, mmap_batch_generator
from openwakeword.train import Model
from openwakeword.utils import AudioFeatures, compute_features_from_generator

# --- torchaudio backend patch ------------------------------------------------
# Newer torchaudio (>=2.9) requires the torchcodec backend, whose DLL fails to
# load on this machine (missing MSVC runtime). openwakeword only uses
# torchaudio.load / torchaudio.info, so route both through soundfile instead.
import torchaudio  # noqa: E402
import soundfile as sf  # noqa: E402
from types import SimpleNamespace  # noqa: E402


def _sf_load(path, frame_offset=0, num_frames=-1):
    data, sr = sf.read(str(path), dtype="float32", always_2d=False)
    data = torch.from_numpy(data.T if data.ndim > 1 else data[None, :])
    if frame_offset or num_frames >= 0:
        end = frame_offset + num_frames if num_frames >= 0 else data.shape[1]
        data = data[:, frame_offset:end]
    return data, sr


def _sf_info(path):
    i = sf.info(str(path))
    return SimpleNamespace(
        samplerate=i.samplerate,
        sample_rate=i.samplerate,
        num_frames=i.frames,
        num_channels=i.channels,
        bits_per_sample=16,
        encoding="PCM_S",
    )


torchaudio.load = _sf_load
torchaudio.info = _sf_info

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger("kimi_train")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--steps", type=int, default=30000, help="training steps")
    ap.add_argument("--data", default=r"models\kimi_wake", help="data dir")
    ap.add_argument("--layer-size", type=int, default=32)
    ap.add_argument("--noise-backgrounds", type=int, default=0,
                    help="generate N synthetic noise background clips (0 = skip background mixing)")
    ap.add_argument("--skip-augment", action="store_true", help="reuse existing feature .npy files")
    ap.add_argument("--gpu", action="store_true", help="use GPU for feature extraction")
    args = ap.parse_args()

    data_dir = os.path.abspath(args.data)
    os.makedirs(data_dir, exist_ok=True)

    # Synthetic background noise clips (car-ish noise for robustness).
    noise_dir = os.path.join(data_dir, "background_noise")
    background_paths = []
    if args.noise_backgrounds > 0:
        os.makedirs(noise_dir, exist_ok=True)
        colors = ["white", "pink", "brown"]
        for i in range(args.noise_backgrounds):
            p = os.path.join(noise_dir, f"bg_{i:03d}.wav")
            if not os.path.exists(p):
                color = colors[i % len(colors)]
                n = 16000 * np.random.randint(3, 8)  # 3-8 s
                clip = (acoustics_noise(n, color) * 0.1).astype(np.int16)
                scipy.io.wavfile.write(p, 16000, clip)
            background_paths.append(p)
        log.info("Using %d background noise clips from %s", len(background_paths), noise_dir)

    # --- total clip length from the median positive clip duration -----------
    positive_test = [str(i) for i in Path(data_dir, "positive_test").glob("*.wav")]
    if not positive_test:
        sys.exit("No positive_test clips found — run gen_clips.py first")
    n = min(50, len(positive_test))
    durations = []
    for _ in range(n):
        sr, dat = scipy.io.wavfile.read(positive_test[np.random.randint(0, len(positive_test))])
        durations.append(len(dat))
    total_length = int(round(np.median(durations) / 1000) * 1000) + 12000
    total_length = max(32000, total_length)
    if abs(total_length - 32000) <= 4000:
        total_length = 32000
    log.info("total clip length = %d samples (%.2fs)", total_length, total_length / 16000)

    feature_save_dir = data_dir
    aug_rounds = 1
    aug_batch = 16

    # --- augment + compute features ----------------------------------------
    feature_targets = {
        "positive_train": ("positive_train", "positive_features_train.npy"),
        "negative_train": ("negative_train", "negative_features_train.npy"),
        "positive_test": ("positive_test", "positive_features_test.npy"),
        "negative_test": ("negative_test", "negative_features_test.npy"),
    }
    n_cpus = max(1, (os.cpu_count() or 1) // 2)

    if args.skip_augment:
        log.info("--skip-augment: assuming feature .npy files already exist")
    else:
        for label, (clip_dir, feat_file) in feature_targets.items():
            out_path = os.path.join(feature_save_dir, feat_file)
            if os.path.exists(out_path):
                log.info("features already exist: %s (skip)", feat_file)
                continue
            clips = [str(i) for i in Path(data_dir, clip_dir).glob("*.wav")] * aug_rounds
            if not clips:
                sys.exit(f"No clips in {clip_dir} — run gen_clips.py first")
            gen = augment_clips(
                clips,
                total_length=total_length,
                batch_size=aug_batch,
                background_clip_paths=background_paths,
                RIR_paths=[],  # no RIR for the lean first model
            )
            log.info("Computing features: %s (%d clips) -> %s", clip_dir, len(clips), feat_file)
            compute_features_from_generator(
                gen,
                n_total=len(clips),
                clip_duration=total_length,
                output_file=out_path,
                device="gpu" if args.gpu and torch.cuda.is_available() else "cpu",
                ncpu=1 if args.gpu else n_cpus,
            )

    # --- build the model -----------------------------------------------------
    input_shape = np.load(os.path.join(feature_save_dir, "positive_features_test.npy")).shape[1:]
    log.info("model input_shape = %s", input_shape)

    oww = Model(
        n_classes=1,
        input_shape=input_shape,
        model_type="dnn",
        layer_dim=args.layer_size,
        seconds_per_example=1280 * input_shape[0] / 16000,
    )

    def f(x, n=input_shape[0]):
        if n > x.shape[1] or n < x.shape[1]:
            x = np.vstack(x)
            new_batch = np.array([x[i:i + n, :] for i in range(0, x.shape[0] - n, n)])
        else:
            return x
        return new_batch

    # label transforms: positive -> 1, everything else -> 0
    label_transforms = {
        "positive": lambda x: [1 for _ in x],
        "adversarial_negative": lambda x: [0 for _ in x],
    }

    feature_data_files = {
        "positive": os.path.join(feature_save_dir, "positive_features_train.npy"),
        "adversarial_negative": os.path.join(feature_save_dir, "negative_features_train.npy"),
    }
    data_transforms = {key: f for key in feature_data_files.keys()}
    batch_n_per_class = {
        "adversarial_negative": 50,
        "positive": 50,
    }

    batch_generator = mmap_batch_generator(
        feature_data_files,
        n_per_class=batch_n_per_class,
        data_transform_funcs=data_transforms,
        label_transform_funcs=label_transforms,
    )

    class IterDataset(torch.utils.data.IterableDataset):
        def __init__(self, generator):
            self.generator = generator

        def __iter__(self):
            return self.generator

    X_train = torch.utils.data.DataLoader(
        IterDataset(batch_generator), batch_size=None, num_workers=n_cpus, prefetch_factor=16
    )

    # False-positive validation data (11.3 hrs of precomputed features).
    fp_path = os.path.join(feature_save_dir, "validation_set_features.npy")
    if not os.path.exists(fp_path):
        sys.exit(
            "Missing validation_set_features.npy (11.3 hr FP set). Download from:\n"
            "  https://huggingface.co/datasets/davidscripka/openwakeword_features/resolve/main/validation_set_features.npy"
        )
    X_val_fp = np.load(fp_path)
    X_val_fp = np.array([X_val_fp[i:i + input_shape[0]] for i in range(0, X_val_fp.shape[0] - input_shape[0], 1)])
    X_val_fp_labels = np.zeros(X_val_fp.shape[0]).astype(np.float32)
    X_val_fp = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(torch.from_numpy(X_val_fp), torch.from_numpy(X_val_fp_labels)),
        batch_size=len(X_val_fp_labels),
    )

    # Positive/negative validation data.
    X_val_pos = np.load(os.path.join(feature_save_dir, "positive_features_test.npy"))
    X_val_neg = np.load(os.path.join(feature_save_dir, "negative_features_test.npy"))
    labels = np.hstack((np.ones(X_val_pos.shape[0]), np.zeros(X_val_neg.shape[0]))).astype(np.float32)
    X_val = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(
            torch.from_numpy(np.vstack((X_val_pos, X_val_neg))), torch.from_numpy(labels)
        ),
        batch_size=len(labels),
    )

    # --- train ----------------------------------------------------------------
    log.info("Starting auto_train (%d steps)...", args.steps)
    best_model = oww.auto_train(
        X_train=X_train,
        X_val=X_val,
        false_positive_val_data=X_val_fp,
        steps=args.steps,
        max_negative_weight=1500,
        target_fp_per_hour=0.2,
    )

    # --- export ---------------------------------------------------------------
    log.info("Exporting ONNX model...")
    oww.export_model(model=best_model, model_name="kimi_wake", output_dir=data_dir)
    log.info("Done. Model: %s", os.path.join(data_dir, "kimi_wake.onnx"))


def acoustics_noise(n, color="white"):
    """Colored noise via the acoustics lib (patched for scipy compat)."""
    import acoustics
    return acoustics.generator.noise(n, color=color)


if __name__ == "__main__":
    main()
