"""
Lean Windows training script for the "ok kimi" wake-word model.

Mirrors the openWakeWord `train.py` flow but skips Piper clip generation
(Linux-only) — clips are pre-generated by `gen_clips.py` (edge-tts). Uses the
openwakeword library API directly:

  augment_clips -> compute_features_from_generator -> mmap_batch_generator
  -> Model.auto_train -> export_model (ONNX)

Usage:
  python tools/kimi_wake/train_wake.py [--steps N] [--data DIR]

Outputs kimi_wake.onnx (+ tflite if onnx2tf available) into the data dir.
"""

import argparse
import glob
import logging
import os
import sys
from pathlib import Path

import numpy as np
import scipy.io.wavfile
import torch

# openwakeword must be importable (pip install -e D:/DEV/openWakeWord)
import openwakeword
from openwakeword.data import augment_clips, mmap_batch_generator, create_fixed_size_clip
from openwakeword.train import Model
from openwakeword.utils import AudioFeatures, compute_features_from_generator

# --- torchaudio backend patch ------------------------------------------------
# Newer torchaudio (>=2.9) requires the torchcodec backend, whose DLL fails to
# load on this machine (missing MSVC runtime). openwakeword only uses
# torchaudio.load / torchaudio.info, so route both through soundfile instead.
import torchaudio  # noqa: E402
import soundfile as sf  # noqa: E402
from types import SimpleNamespace  # noqa: E402


def _sf_load(path, frame_offset=0, num_frames=-1):
    data, sr = sf.read(str(path), dtype="float32", always_2d=False)
    data = torch.from_numpy(data.T if data.ndim > 1 else data[None, :])
    if frame_offset or num_frames >= 0:
        end = frame_offset + num_frames if num_frames >= 0 else data.shape[1]
        data = data[:, frame_offset:end]
    return data, sr


def _sf_info(path):
    i = sf.info(str(path))
    return SimpleNamespace(
        samplerate=i.samplerate,
        sample_rate=i.samplerate,
        num_frames=i.frames,
        num_channels=i.channels,
        bits_per_sample=16,
        encoding="PCM_S",
    )


torchaudio.load = _sf_load
torchaudio.info = _sf_info

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger("kimi_train")


class IterDataset(torch.utils.data.IterableDataset):
    """Module-level so multiprocessing DataLoader workers can pickle it."""

    def __init__(self, generator):
        self.generator = generator

    def __iter__(self):
        return self.generator


def augment_clips_random_pos(clip_paths, total_length, sr=16000, batch_size=128,
                             background_clip_paths=[], RIR_paths=[]):
    """Like openwakeword.data.augment_clips but places each clip at a RANDOM
    position within the window (create_fixed_size_clip start randomized).

    The stock augment_clips end-anchors every clip (phrase always near the
    window end), which makes the model POSITION-SENSITIVE — in streaming the
    phrase scrolls through many positions and the model over-fires on speech
    it would reject at the training position. Randomizing start teaches
    position invariance (matching how real wake-word audio arrives).

    Yields batches of (batch_size, total_length) int16 PCM like augment_clips.
    """
    import audiomentations
    import torch_audiomentations

    probs = {
        "SevenBandParametricEQ": 0.25, "TanhDistortion": 0.25,
        "PitchShift": 0.25, "BandStopFilter": 0.25, "AddColoredNoise": 0.25,
        "AddBackgroundNoise": 0.75, "Gain": 1.0, "RIR": 0.5,
    }
    augment1 = audiomentations.Compose([
        audiomentations.SevenBandParametricEQ(min_gain_db=-6, max_gain_db=6, p=probs["SevenBandParametricEQ"]),
        audiomentations.TanhDistortion(min_distortion=0.0001, max_distortion=0.10, p=probs["TanhDistortion"]),
    ])
    if background_clip_paths:
        augment2 = torch_audiomentations.Compose([
            torch_audiomentations.PitchShift(min_transpose_semitones=-3, max_transpose_semitones=3,
                                             p=probs["PitchShift"], sample_rate=16000, mode="per_batch"),
            torch_audiomentations.BandStopFilter(p=probs["BandStopFilter"], mode="per_batch"),
            torch_audiomentations.AddColoredNoise(min_snr_in_db=10, max_snr_in_db=30,
                                                  min_f_decay=-1, max_f_decay=2, p=probs["AddColoredNoise"], mode="per_batch"),
            torch_audiomentations.AddBackgroundNoise(p=probs["AddBackgroundNoise"], background_paths=background_clip_paths,
                                                     min_snr_in_db=-10, max_snr_in_db=15, mode="per_batch"),
            torch_audiomentations.Gain(max_gain_in_db=0, p=probs["Gain"]),
        ])
    else:
        augment2 = torch_audiomentations.Compose([
            torch_audiomentations.PitchShift(min_transpose_semitones=-3, max_transpose_semitones=3,
                                             p=probs["PitchShift"], sample_rate=16000, mode="per_batch"),
            torch_audiomentations.BandStopFilter(p=probs["BandStopFilter"], mode="per_batch"),
            torch_audiomentations.AddColoredNoise(min_snr_in_db=10, max_snr_in_db=30,
                                                  min_f_decay=-1, max_f_decay=2, p=probs["AddColoredNoise"], mode="per_batch"),
            torch_audiomentations.Gain(max_gain_in_db=0, p=probs["Gain"]),
        ])

    for i in range(0, len(clip_paths), batch_size):
        batch = clip_paths[i:i + batch_size]
        augmented = []
        for clip in batch:
            clip_data, clip_sr = torchaudio.load(clip)
            clip_data = clip_data[0]
            if clip_data.shape[0] > total_length:
                clip_data = clip_data[0:total_length]
            if clip_sr != sr:
                raise ValueError("Error! Clip does not have the correct sample rate!")
            # RANDOM start position (0..total_length-len), so the phrase is not
            # always end-anchored → position-invariant model.
            max_start = max(0, total_length - int(clip_data.shape[0]))
            start = np.random.randint(0, max_start + 1) if max_start > 0 else 0
            clip_data = create_fixed_size_clip(clip_data, total_length, clip_sr, start=start)
            augmented.append(torch.from_numpy(augment1(samples=clip_data, sample_rate=sr)))

        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
        aug_batch = augment2(samples=torch.vstack(augmented).unsqueeze(dim=1).to(device), sample_rate=sr).squeeze(axis=1)
        yield (aug_batch.cpu().numpy() * 32767).astype(np.int16)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--steps", type=int, default=30000, help="training steps")
    ap.add_argument("--data", default=r"models\kimi_wake", help="data dir")
    ap.add_argument("--layer-size", type=int, default=32)
    ap.add_argument("--noise-backgrounds", type=int, default=0,
                    help="generate N synthetic noise background clips (0 = skip background mixing)")
    ap.add_argument("--skip-augment", action="store_true", help="reuse existing feature .npy files")
    ap.add_argument("--gpu", action="store_true", help="use GPU for feature extraction")
    ap.add_argument("--max-negative-weight", type=int, default=1500,
                    help="max negative class weight in auto_train (lower = gentler on positives)")
    ap.add_argument("--target-fp-per-hour", type=float, default=0.2,
                    help="FP/hr target fed to auto_train (higher = stops doubling negative weight sooner)")
    ap.add_argument("--real-negatives", type=str, default=None, metavar="NPY",
                    help="real-audio negative features (real_negative_features_train.npy) to add as a class")
    ap.add_argument("--random-pos", action="store_true",
                    help="randomize wake-phrase position in the window (position-invariant model)")
    args = ap.parse_args()

    data_dir = os.path.abspath(args.data)
    os.makedirs(data_dir, exist_ok=True)

    # Synthetic background noise clips (car-ish noise for robustness).
    noise_dir = os.path.join(data_dir, "background_noise")
    background_paths = []
    if args.noise_backgrounds > 0:
        os.makedirs(noise_dir, exist_ok=True)
        colors = ["white", "pink", "brown"]
        for i in range(args.noise_backgrounds):
            p = os.path.join(noise_dir, f"bg_{i:03d}.wav")
            if not os.path.exists(p):
                color = colors[i % len(colors)]
                n = 16000 * np.random.randint(3, 8)  # 3-8 s
                clip = (acoustics_noise(n, color) * 0.1).astype(np.int16)
                scipy.io.wavfile.write(p, 16000, clip)
            background_paths.append(p)
        log.info("Using %d background noise clips from %s", len(background_paths), noise_dir)

    # --- total clip length from the median positive clip duration -----------
    positive_test = [str(i) for i in Path(data_dir, "positive_test").glob("*.wav")]
    if not positive_test:
        sys.exit("No positive_test clips found — run gen_clips.py first")
    n = min(50, len(positive_test))
    durations = []
    for _ in range(n):
        sr, dat = scipy.io.wavfile.read(positive_test[np.random.randint(0, len(positive_test))])
        durations.append(len(dat))
    total_length = int(round(np.median(durations) / 1000) * 1000) + 12000
    total_length = max(32000, total_length)
    if abs(total_length - 32000) <= 4000:
        total_length = 32000
    log.info("total clip length = %d samples (%.2fs)", total_length, total_length / 16000)

    feature_save_dir = data_dir
    aug_rounds = 1
    aug_batch = 16

    # --- augment + compute features ----------------------------------------
    feature_targets = {
        "positive_train": ("positive_train", "positive_features_train.npy"),
        "negative_train": ("negative_train", "negative_features_train.npy"),
        "positive_test": ("positive_test", "positive_features_test.npy"),
        "negative_test": ("negative_test", "negative_features_test.npy"),
    }
    n_cpus = max(1, (os.cpu_count() or 1) // 2)

    if args.skip_augment:
        log.info("--skip-augment: assuming feature .npy files already exist")
    else:
        for label, (clip_dir, feat_file) in feature_targets.items():
            out_path = os.path.join(feature_save_dir, feat_file)
            if os.path.exists(out_path):
                log.info("features already exist: %s (skip)", feat_file)
                continue
            clips = [str(i) for i in Path(data_dir, clip_dir).glob("*.wav")] * aug_rounds
            if not clips:
                sys.exit(f"No clips in {clip_dir} — run gen_clips.py first")
            if args.random_pos:
                log.info("Using RANDOMIZED phrase position (position-invariant training)")
                gen = augment_clips_random_pos(
                    clips,
                    total_length=total_length,
                    batch_size=aug_batch,
                    background_clip_paths=background_paths,
                    RIR_paths=[],
                )
            else:
                gen = augment_clips(
                    clips,
                    total_length=total_length,
                    batch_size=aug_batch,
                    background_clip_paths=background_paths,
                    RIR_paths=[],  # no RIR for the lean first model
                )
            log.info("Computing features: %s (%d clips) -> %s", clip_dir, len(clips), feat_file)
            compute_features_from_generator(
                gen,
                n_total=len(clips),
                clip_duration=total_length,
                output_file=out_path,
                device="gpu" if args.gpu and torch.cuda.is_available() else "cpu",
                ncpu=1 if args.gpu else n_cpus,
            )

    # --- build the model -----------------------------------------------------
    input_shape = np.load(os.path.join(feature_save_dir, "positive_features_test.npy")).shape[1:]
    log.info("model input_shape = %s", input_shape)

    oww = Model(
        n_classes=1,
        input_shape=input_shape,
        model_type="dnn",
        layer_dim=args.layer_size,
        seconds_per_example=1280 * input_shape[0] / 16000,
    )

    def f(x, n=input_shape[0]):
        if n > x.shape[1] or n < x.shape[1]:
            x = np.vstack(x)
            new_batch = np.array([x[i:i + n, :] for i in range(0, x.shape[0] - n, n)])
        else:
            return x
        return new_batch

    # label transforms: positive -> 1, everything else -> 0
    label_transforms = {
        "positive": lambda x: [1 for _ in x],
        "adversarial_negative": lambda x: [0 for _ in x],
    }

    feature_data_files = {
        "positive": os.path.join(feature_save_dir, "positive_features_train.npy"),
        "adversarial_negative": os.path.join(feature_save_dir, "negative_features_train.npy"),
    }
    data_transforms = {key: f for key in feature_data_files.keys()}
    batch_n_per_class = {
        "adversarial_negative": 50,
        "positive": 50,
    }

    # Optional real-audio negatives (built by build_real_negatives.py). Training
    # on REAL speech/music/noise features is what fixes over-firing on real-world
    # audio — synthetic-only negatives leave real audio in the positive region.
    if args.real_negatives is None:
        auto_real = os.path.join(feature_save_dir, "real_negative_features_train.npy")
        if os.path.exists(auto_real):
            args.real_negatives = auto_real
    if args.real_negatives:
        rn_path = os.path.abspath(args.real_negatives)
        if not os.path.exists(rn_path):
            sys.exit(f"--real-negatives file not found: {rn_path}")
        feature_data_files["real_negative"] = rn_path
        label_transforms["real_negative"] = lambda x: [0 for _ in x]
        data_transforms["real_negative"] = f
        batch_n_per_class["real_negative"] = 50
        log.info("Adding real-audio negatives: %s", rn_path)

    batch_generator = mmap_batch_generator(
        feature_data_files,
        n_per_class=batch_n_per_class,
        data_transform_funcs=data_transforms,
        label_transform_funcs=label_transforms,
    )

    X_train = torch.utils.data.DataLoader(
        IterDataset(batch_generator), batch_size=None, num_workers=0, prefetch_factor=None
    )

    # False-positive validation data (real-audio features). Prefer the held-out
    # portion (validation_set_holdout.npy) when real negatives were built from the
    # full set — otherwise we'd validate on audio the model already trained on.
    fp_path = os.path.join(feature_save_dir, "validation_set_holdout.npy")
    if not os.path.exists(fp_path):
        fp_path = os.path.join(feature_save_dir, "validation_set_features.npy")
    if not os.path.exists(fp_path):
        sys.exit(
            "Missing validation_set_features.npy (11.3 hr FP set). Download from:\n"
            "  https://huggingface.co/datasets/davidscripka/openwakeword_features/resolve/main/validation_set_features.npy"
        )
    log.info("FP validation: %s", os.path.basename(fp_path))
    X_val_fp = np.load(fp_path)
    X_val_fp = np.array([X_val_fp[i:i + input_shape[0]] for i in range(0, X_val_fp.shape[0] - input_shape[0], 1)])
    X_val_fp_labels = np.zeros(X_val_fp.shape[0]).astype(np.float32)
    X_val_fp = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(torch.from_numpy(X_val_fp), torch.from_numpy(X_val_fp_labels)),
        batch_size=len(X_val_fp_labels),
    )

    # Positive/negative validation data.
    X_val_pos = np.load(os.path.join(feature_save_dir, "positive_features_test.npy"))
    X_val_neg = np.load(os.path.join(feature_save_dir, "negative_features_test.npy"))
    labels = np.hstack((np.ones(X_val_pos.shape[0]), np.zeros(X_val_neg.shape[0]))).astype(np.float32)
    X_val = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(
            torch.from_numpy(np.vstack((X_val_pos, X_val_neg))), torch.from_numpy(labels)
        ),
        batch_size=len(labels),
    )

    # --- train ----------------------------------------------------------------
    log.info("Starting auto_train (%d steps, max_neg_weight=%d, target_fp/hr=%.2f)...",
             args.steps, args.max_negative_weight, args.target_fp_per_hour)
    best_model = oww.auto_train(
        X_train=X_train,
        X_val=X_val,
        false_positive_val_data=X_val_fp,
        steps=args.steps,
        max_negative_weight=args.max_negative_weight,
        target_fp_per_hour=args.target_fp_per_hour,
    )

    # --- export ---------------------------------------------------------------
    log.info("Exporting ONNX model...")
    try:
        oww.export_model(model=best_model, model_name="kimi_wake", output_dir=data_dir)
    except Exception:
        # torch 2.13's default (dynamo) exporter needs onnxscript; fall back to
        # the legacy exporter, which only needs the onnx package.
        import copy
        import torch as _torch

        log.info("dynamo exporter unavailable (onnxscript missing); using legacy exporter")
        model_to_save = copy.deepcopy(best_model)
        _torch.onnx.export(
            model_to_save.to("cpu"),
            _torch.rand(oww.input_shape)[None, ],
            os.path.join(data_dir, "kimi_wake.onnx"),
            opset_version=13,
            dynamo=False,
        )
    log.info("Done. Model: %s", os.path.join(data_dir, "kimi_wake.onnx"))


def acoustics_noise(n, color="white"):
    """Colored noise via the acoustics lib (patched for scipy compat)."""
    import acoustics
    return acoustics.generator.noise(n, color=color)


if __name__ == "__main__":
    main()
